### ISSUE TITLE
Change the backend setup variable used for setting up cache

### ISSUE THREAD

**Issue by sac** [gluster/gluster-ansible#71]
Currently we use the following variable for setting up cache:

```
     gluster_infra_cache_vars:
       - vgname: vg_vdc
         cachedisk: '/dev/vdd'
         cachelvname: 'cachelv_thinpool_vg_vdc'
         cachethinpoolname: 'thinpool_vg_vdc'
         cachelvsize: '50G'
         cachemetalvsize: '2G'
         cachemetalvname: 'cache_thinpool_vg_vdc'
         cachemode: 'writethrough'
```
We currently mention the disk which has to be used for setting up the cache.
And internally use this device to extend the volume group vg_vdc. However since Ansible 2.8
this will not work. We have to  also mention the disks which are currently part of the volume group vg_vdc.

For example if vg_vdc is made of /dev/vdb then the variable should look like:

```
     gluster_infra_cache_vars:
       - vgname: vg_vdc
         cachedisk: '/dev/vdc,/dev/vdd'
         cachelvname: 'cachelv_thinpool_vg_vdc'
         cachethinpoolname: 'thinpool_vg_vdc'
         cachelvsize: '50G'
         cachemetalvsize: '2G'
         cachemetalvname: 'cache_thinpool_vg_vdc'
         cachemode: 'writethrough'
```
