### ISSUE TITLE
Clarify usage from ansible

### ISSUE THREAD

**Issue by nicobo** [gluster/gluster-ansible#81]
Gluster doc directly leads to https://github.com/gluster/gluster-ansible as the preferred way to install and configure glusterfs for ansible users.

However this GitHub project doesn't clearly states how to use it from ansible :

- is it available at ansible Galaxy?
- it seems parts have been integrated into the official ansible modules but not all (?)
- is it a plain ansible module (I couldn't make it work as-is)
- does it require to download each submodules separately

It would be nice to clarify this, thanks!

**Comment by sac** [comment]
@nicobo you can download and install the packages from https://copr.fedorainfracloud.org/coprs/sac/gluster-ansible/packages/ for fedora or rhel.

All of the module used in gluster-ansible are integrated into ansible. You don't have to install any modules separately.

You have to define role variables and write a playbook to be called by ansible-playbook. If you download all the packages and install gluster-ansible it'll take care of installing others since it depends on them.

Examples to writing playbooks and variables can be found here: https://github.com/gluster/gluster-ansible/tree/master/playbooks

**Comment by nicobo** [comment]
Thanks.

Therefore I would suggest to make the Quick Start Guide simply point at the official ansible docs rather than the GitHub repo.

**Comment by eoli3n** [comment]
How to install roles for debian ? 
Why is this not available on galaxy ?

**Comment by outdooracorn** [comment]
It too was expecting these to be on Ansible Galaxy.

For anyone interested, you can install these the "Galaxy way" by adding the following to your `requirements.yml` file:
```yaml
- name: gluster.infra
  src: https://github.com/gluster/gluster-ansible-infra.git

# .git at end or URL is optional
- name: gluster.cluster
  src: https://github.com/gluster/gluster-ansible-cluster

# the `name` parameter is also optional but then it installs it to gluster-ansible-features
# instead of gluster.features (or whatever you set `name` to)
- src: https://github.com/gluster/gluster-ansible-features

# repeat for each you want to install...
```
And run with `ansible-galaxy install -r requirements.yml` as usual. E.g.:
```bash
$ ansible-galaxy install -r requirements.yml
- extracting gluster.infra to /home/ollie/.ansible/roles/gluster.infra
- gluster.infra was installed successfully
- extracting gluster.cluster to /home/ollie/.ansible/roles/gluster.cluster
- gluster.cluster was installed successfully
- extracting gluster-ansible-features to /home/ollie/.ansible/roles/gluster-ansible-features
- gluster-ansible-features was installed successfully
```
