### ISSUE TITLE
Add gluster.install role

### ISSUE THREAD

**Issue by eoli3n** [gluster/gluster-ansible#83]
something like 

```
# for debian buster
---
- name: Add glusterfs key
  apt_key:
    url: https://download.gluster.org/pub/gluster/glusterfs/7/rsa.pub
    state: present

- name: Add glusterfs repo
  apt_repository:
    repo: 'deb [arch=amd64] https://download.gluster.org/pub/gluster/glusterfs/7/LATEST/Debian/buster/amd64/apt buster main'
    state: present

- name: Install deps
  apt:
    name:
      - lvm2
      - xfsprogs
    state: present

- name: Install gluster server
  apt:
    name: glusterfs-server

- name: Start and enable service
  service:
    name: glusterd
    state: restarted
```
